version: '3.4'

services:
  # Database
  catalogdb:
    image: mongo
  mongo-express:
    image: mongo-express:latest
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres
  orderdb:
    image: postgres

  # Utilities
  portainer:
    image: portainer/portainer-ce
  pgadmin:
    image: dpage/pgadmin4
  rabbitmq:
    image: rabbitmq:3-management-alpine
  redis-webui:
    image: rediscommander/redis-commander:latest

  # Services
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile
  
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_discountDb:
  postgres_orderDb:
  pgadmin_data:
